export {default as bengkelCover} from './img/bengkel.jpg'
export {default as comingSoonCover} from './img/coming soon.jpg'
export {default as hmsiProjectCover} from './img/HMSI.jpg'
export {default as imgProfile} from './img/image 125.jpg'
export {default as originalProfile} from './img/original.png'
export {default as technofestCover} from './img/technofest.jpg'
export {default as technoshiftCover} from './img/technoshift2.jpg'
export {default as webCoffeeShopCover} from './img/web project.jpg'
export {default as petaniGoCover} from './img/petani go.jpg'
export {default as disneyCloneCover} from './img/image.png'
export {default as slideTandaBaca1} from './img/slide web coffeshop.jpg'
export {default as slideTandaBaca2} from './img/slide 2 web coffeeshop.jpg'
export {default as slidePetaniGo1} from './img/slide 8.jpg'
export {default as slidePetaniGo2} from './img/slide 9.jpg'
export {default as slidePetaniGo3} from './img/slide 10.jpg'
export {default as slidePetaniGo4} from './img/slide 11.jpg'
export {default as slidePetaniGo5} from './img/slide 12.jpg'
export {default as slideBengkel1} from './img/Slide Bengkel 1.jpg'
export {default as slideBengkel2} from './img/Slide Bengkel 2.jpg'
export {default as slideBengkel3} from './img/Slide Bengkel 3.jpg'
export {default as slideDisneyClone1} from './img/Slide Disney 1.jpg'
export {default as slideDisneyClone2} from './img/Slide Disney 2.jpg'
export {default as coverDisneyClone} from './img/Disneyclone Cover Pages.jpg'
export {default as lightImg} from './img/light.JPG'
export {default as darkImg} from './img/dark.JPG'

// PDF
export {default as cvEnglish} from './PDF/CV Muhammad Chairul Wibisono_English.pdf'
export {default as cvIndo} from './PDF/CV Muhammad Chairul Wibisono_Indonesia.pdf'